//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.netlab.viplink.model;

import static org.junit.Assert.*;

import org.junit.Test;

import java.util.UUID;

import com.hp.api.Id;

/**
 * Sample test of the SwitchFlow domain model.
 */
public class SwitchFlowTest {

    @Test
    public void basic() {
        SwitchFlow s = new SwitchFlow("Gizmo");
        assertEquals("incorrect name", "Gizmo", s.name());
    }

}
