//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.netlab.viplink.model;

/**
 * SwitchFlow sort attribute.
 */
public enum SwitchFlowSortAttribute {

    /** Sorts by name */
    NAME,
    DPID

}
