//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.netlab.viplink.ui;

import org.apache.felix.scr.annotations.Component;

import com.hp.sdn.ui.misc.SelfRegisteringUIExtension;

/**
 * VIPLink Flow Modifier UI extension, which provides additional UI elements to the
 * HP SDN Controller GUI.
 */
@Component
public class UIExtension extends SelfRegisteringUIExtension {
    
    /** Create the core UI elements contributor. */
    public UIExtension() {
        super("viplink", "com/netlab/viplink/ui", UIExtension.class);
    }

}
