//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.netlab.viplink.rs;

import static org.easymock.EasyMock.createMock;
import static org.easymock.EasyMock.expect;
import static org.easymock.EasyMock.replay;
import static org.easymock.EasyMock.verify;

import java.util.UUID;

import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;

import javax.ws.rs.core.MediaType;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.hp.util.rs.ResourceTest;
import com.hp.sdn.rs.misc.ControllerResourceTest;

import com.netlab.viplink.model.SwitchFlow;
import com.netlab.viplink.api.SwitchFlowService;

import com.hp.api.Id;


/**
 * Sample SwitchFlow REST API resource.
 */
public class SwitchFlowResourceTest extends ControllerResourceTest {

    private SwitchFlowService svc;
    
    /**
     * Creates a test suite on the default package set.
     */
    public SwitchFlowResourceTest() {
        super("com.netlab.viplink.rs");
    }
    

    @Override
    @Before
    public void setUp() throws Exception {
        super.setUp();
        svc = createMock(SwitchFlowService.class);

        sl.register(SwitchFlowService.class, svc,
                    Collections.<String, Object> emptyMap());

        // If a specific test case expects a different format, such
        // format will have to be set calling this method.
        ResourceTest.setDefaultMediaType(MediaType.APPLICATION_JSON);
    }
    
    @Override
    @After
    public void tearDown() throws Exception {
        super.tearDown();
        sl.unregister(SwitchFlowService.class, svc);
    }   
/*
    @Test
    public void addSwitchFlow() {
        SwitchFlow s = new SwitchFlow("Thingie");
        
        expect(svc.create("Thingie"))
            .andReturn(s);
        replay(svc);
        
        String r = post("VIP",  
                        "{\"item\":{\"name\":\"Thingie\"}}");
        assertResponseContains(r, "\"uid\":\"" + s.getId().getValue() + "\"", "\"name\":\"Thingie\"");
        verify(svc);
    }

    @Test
    public void getSwitchFlow() {
        Id<SwitchFlow, UUID> id = Id.valueOf(UUID.randomUUID());
        
        expect(svc.get(id)).andReturn(new SwitchFlow(id, "Thingie"));
        replay(svc);
        
        String r = get("VIP/" + id.getValue());
        assertResponseContains(r, "\"uid\":\"" + id.getValue() + "\"", "\"name\":\"Thingie\"");
        verify(svc);
    }

    @Test
    public void getAll() {
        Id<SwitchFlow, UUID> id1 = Id.valueOf(UUID.randomUUID());
        Id<SwitchFlow, UUID> id2 = Id.valueOf(UUID.randomUUID());

        Collection<SwitchFlow> c = new HashSet<SwitchFlow>();
        c.add(new SwitchFlow(id1, "Thingie"));
        c.add(new SwitchFlow(id2, "Doo-Hickey"));
        expect(svc.getAll()).andReturn(c);
        replay(svc);

        String r = get("VIP");
        assertResponseContains(r, "\"VIP\":[",
                               "{\"uid\":\"" + id1.getValue() + "\"", "{\"uid\":\"" + id2.getValue() + "\"");
        verify(svc);
    }

    @Test
    public void deleteSwitchFlow() {
        Id<SwitchFlow, UUID> id = Id.valueOf(UUID.randomUUID());
        
        svc.delete(id);
        replay(svc);
        
        String r = delete("VIP/" + id.getValue());
        verify(svc);
    }
    */
}
