//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.netlab.viplink.impl;

import static org.junit.Assert.*;

import java.util.UUID;

import com.hp.api.NotFoundException;

import com.netlab.viplink.model.SwitchFlow;
import com.netlab.viplink.api.SwitchFlowService;

import com.hp.api.Id;

import org.junit.Before;
import org.junit.Test;

/**
 * Sample test of the SwitchFlow service implementation.
 */
public class SwitchFlowManagerTest {
  
    private SwitchFlowService svc;
/*
    @Before
    public void setUp() {
        svc = new SwitchFlowManager();
    }
  
    @Test
    public void basics() {
        SwitchFlow s = svc.create("Gizmo");
        assertNotNull("incorrect create", s.getId());
        assertEquals("incorrect get", s, svc.get(s.getId()));
        assertEquals("incorrect name", "Gizmo", s.name());
        svc.delete(s.getId());
        try{
            svc.get(s.getId());
            fail("Expected exception");
        } catch(NotFoundException e) {
            
        }
    }

    @Test
    public void defaults() {
        SwitchFlow s = svc.create(null);
        assertNotNull("incorrect id", s.getId());
        assertNotNull("incorrect name", s.name());
    }

    @Test(expected=NotFoundException.class)
    public void notFound() {
        Id<SwitchFlow, UUID> id = Id.valueOf(UUID.randomUUID());
        svc.get(id);
    }
    */
}
